FROM python:3.11

WORKDIR /src/app

COPY . .

RUN python -m venv venv

RUN ./venv/bin/pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Comando para rodar o Gunicorn
CMD ["./venv/bin/gunicorn", "--bind", "0.0.0.0:5000", "run:app"]